# Generated by Django 5.1 on 2024-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerisationTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(verbose_name='Описание')),
                ('parse_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Компьютерная техника',
                'verbose_name_plural': 'Компьютерная техника',
                'ordering': ['-price', 'description'],
            },
        ),
    ]
