# Generated by Django 5.1 on 2024-08-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computerisationtechnical',
            options={'ordering': ['parse_datetime', '-price'], 'verbose_name': 'Компьютерная техника', 'verbose_name_plural': 'Компьютерная техника'},
        ),
    ]
