# Generated by Django 5.1 on 2024-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_computerisationtechnical_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerisationtechnical',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
